//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace CCMS.Entities {
    
    
    /// <summary>
    /// <para>Display Name: Auto number configuration</para>
    /// </summary>
    [EntityLogicalName("dia_autonumberconfiguration")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_autonumberconfiguration : ExtendedEntity<dia_autonumberconfigurationState, dia_autonumberconfiguration_statuscode> {
        
        public const string EntityLogicalName = "dia_autonumberconfiguration";
        
        public const int EntityTypeCode = 10191;
        
        public dia_autonumberconfiguration() : 
                base(EntityLogicalName) {
        }
        
        public dia_autonumberconfiguration(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("dia_name");
            }
        }
        
        [AttributeLogicalName("dia_autonumberconfigurationid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_autonumberconfigurationid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for entity instances</para>
        /// <para>Display Name: Auto Number Configuration</para>
        /// </summary>
        [AttributeLogicalName("dia_autonumberconfigurationid")]
        public Guid? dia_autonumberconfigurationId {
            get {
                return GetAttributeValue<Guid?>("dia_autonumberconfigurationid");
            }
            set {
                SetId("dia_autonumberconfigurationid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the record.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the record.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Sequence number of the import that created this record.</para>
        /// <para>Display Name: Import Sequence Number</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who modified the record.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the record was modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the record.</para>
        /// <para>Display Name: Modified By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Date and time that the record was migrated.</para>
        /// <para>Display Name: Record Created On</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        public DateTime? OverriddenCreatedOn {
            get {
                return GetAttributeValue<DateTime?>("overriddencreatedon");
            }
            set {
                SetAttributeValue("overriddencreatedon", value);
            }
        }
        
        /// <summary>
        /// <para>Owner Id</para>
        /// <para>Display Name: Owner</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the business unit that owns the record</para>
        /// <para>Display Name: Owning Business Unit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the team that owns the record.</para>
        /// <para>Display Name: Owning Team</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for the user that owns the record.</para>
        /// <para>Display Name: Owning User</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Time Zone Rule Version Number</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        public int? TimeZoneRuleVersionNumber {
            get {
                return GetAttributeValue<int?>("timezoneruleversionnumber");
            }
            set {
                SetAttributeValue("timezoneruleversionnumber", value);
            }
        }
        
        /// <summary>
        /// <para>Time zone code that was in use when the record was created.</para>
        /// <para>Display Name: UTC Conversion Time Zone Code</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        public int? UTCConversionTimeZoneCode {
            get {
                return GetAttributeValue<int?>("utcconversiontimezonecode");
            }
            set {
                SetAttributeValue("utcconversiontimezonecode", value);
            }
        }
        
        /// <summary>
        /// <para>Version Number</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>Display Name: Attribute Schema Name</para>
        /// </summary>
        [AttributeLogicalName("dia_attributeschemaname")]
        public string dia_attributeschemaname {
            get {
                return GetAttributeValue<string>("dia_attributeschemaname");
            }
            set {
                SetAttributeValue("dia_attributeschemaname", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Description</para>
        /// </summary>
        [AttributeLogicalName("dia_description")]
        public string dia_description {
            get {
                return GetAttributeValue<string>("dia_description");
            }
            set {
                SetAttributeValue("dia_description", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Entity Schema Name</para>
        /// </summary>
        [AttributeLogicalName("dia_entityschemaname")]
        public string dia_entityschemaname {
            get {
                return GetAttributeValue<string>("dia_entityschemaname");
            }
            set {
                SetAttributeValue("dia_entityschemaname", value);
            }
        }
        
        /// <summary>
        /// <para>The name of the custom entity.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("dia_name")]
        public string dia_name {
            get {
                return GetAttributeValue<string>("dia_name");
            }
            set {
                SetAttributeValue("dia_name", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Next Unique Identifier</para>
        /// </summary>
        [AttributeLogicalName("dia_nextuniqueidentifier")]
        public int? dia_nextuniqueidentifier {
            get {
                return GetAttributeValue<int?>("dia_nextuniqueidentifier");
            }
            set {
                SetAttributeValue("dia_nextuniqueidentifier", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Number of Characters</para>
        /// </summary>
        [AttributeLogicalName("dia_numberofcharacters")]
        public int? dia_numberofcharacters {
            get {
                return GetAttributeValue<int?>("dia_numberofcharacters");
            }
            set {
                SetAttributeValue("dia_numberofcharacters", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Obfuscate</para>
        /// </summary>
        [AttributeLogicalName("dia_obfuscate")]
        public bool? dia_obfuscate {
            get {
                return GetAttributeValue<bool?>("dia_obfuscate");
            }
            set {
                SetAttributeValue("dia_obfuscate", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Prefix</para>
        /// </summary>
        [AttributeLogicalName("dia_prefix")]
        public string dia_prefix {
            get {
                return GetAttributeValue<string>("dia_prefix");
            }
            set {
                SetAttributeValue("dia_prefix", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Random</para>
        /// </summary>
        [AttributeLogicalName("dia_random")]
        public bool? dia_random {
            get {
                return GetAttributeValue<bool?>("dia_random");
            }
            set {
                SetAttributeValue("dia_random", value);
            }
        }
        
        /// <summary>
        /// <para>Display Name: Update Key</para>
        /// </summary>
        [AttributeLogicalName("dia_updatekey")]
        public string dia_updatekey {
            get {
                return GetAttributeValue<string>("dia_updatekey");
            }
            set {
                SetAttributeValue("dia_updatekey", value);
            }
        }
        
        /// <summary>
        /// <para>Status of the Auto Number Configuration</para>
        /// <para>Display Name: State</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        public dia_autonumberconfigurationState? statecode {
            get {
                return GetOptionSetValue<dia_autonumberconfigurationState>("statecode");
            }
            set {
                SetOptionSetValue("statecode", value);
            }
        }
        
        /// <summary>
        /// <para>Reason for the status of the Auto Number Configuration</para>
        /// <para>Display Name: Status</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public dia_autonumberconfiguration_statuscode? statuscode {
            get {
                return GetOptionSetValue<dia_autonumberconfiguration_statuscode>("statuscode");
            }
            set {
                SetOptionSetValue("statuscode", value);
            }
        }
        
        [AttributeLogicalName("owningbusinessunit")]
        [RelationshipSchemaName("business_unit_dia_autonumberconfiguration")]
        public BusinessUnit business_unit_dia_autonumberconfiguration {
            get {
                return GetRelatedEntity<BusinessUnit>("business_unit_dia_autonumberconfiguration", null);
            }
            set {
                SetRelatedEntity("business_unit_dia_autonumberconfiguration", null, value);
            }
        }
        
        [AttributeLogicalName("createdby")]
        [RelationshipSchemaName("lk_dia_autonumberconfiguration_createdby")]
        public SystemUser lk_dia_autonumberconfiguration_createdby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_autonumberconfiguration_createdby", null);
            }
            set {
                SetRelatedEntity("lk_dia_autonumberconfiguration_createdby", null, value);
            }
        }
        
        [AttributeLogicalName("createdonbehalfby")]
        [RelationshipSchemaName("lk_dia_autonumberconfiguration_createdonbehalfby")]
        public SystemUser lk_dia_autonumberconfiguration_createdonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_autonumberconfiguration_createdonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_autonumberconfiguration_createdonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedby")]
        [RelationshipSchemaName("lk_dia_autonumberconfiguration_modifiedby")]
        public SystemUser lk_dia_autonumberconfiguration_modifiedby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_autonumberconfiguration_modifiedby", null);
            }
            set {
                SetRelatedEntity("lk_dia_autonumberconfiguration_modifiedby", null, value);
            }
        }
        
        [AttributeLogicalName("modifiedonbehalfby")]
        [RelationshipSchemaName("lk_dia_autonumberconfiguration_modifiedonbehalfby")]
        public SystemUser lk_dia_autonumberconfiguration_modifiedonbehalfby {
            get {
                return GetRelatedEntity<SystemUser>("lk_dia_autonumberconfiguration_modifiedonbehalfby", null);
            }
            set {
                SetRelatedEntity("lk_dia_autonumberconfiguration_modifiedonbehalfby", null, value);
            }
        }
        
        [AttributeLogicalName("owningteam")]
        [RelationshipSchemaName("team_dia_autonumberconfiguration")]
        public Team team_dia_autonumberconfiguration {
            get {
                return GetRelatedEntity<Team>("team_dia_autonumberconfiguration", null);
            }
            set {
                SetRelatedEntity("team_dia_autonumberconfiguration", null, value);
            }
        }
        
        [AttributeLogicalName("owninguser")]
        [RelationshipSchemaName("user_dia_autonumberconfiguration")]
        public SystemUser user_dia_autonumberconfiguration {
            get {
                return GetRelatedEntity<SystemUser>("user_dia_autonumberconfiguration", null);
            }
            set {
                SetRelatedEntity("user_dia_autonumberconfiguration", null, value);
            }
        }
        
        public static dia_autonumberconfiguration Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_autonumberconfiguration,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum dia_autonumberconfigurationState {
        
        [EnumMember()]
        Active = 0,
        
        [EnumMember()]
        Inactive = 1,
    }
    
    [DataContract()]
    public enum dia_autonumberconfiguration_statuscode {
        
        [EnumMember()]
        Active = 1,
        
        [EnumMember()]
        Inactive = 2,
    }
}
