//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace CCMS.Entities {
    
    
    [EntityLogicalName("dia_product_applicationtype")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class dia_product_applicationtype : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "dia_product_applicationtype";
        
        public const int EntityTypeCode = 10296;
        
        public dia_product_applicationtype() : 
                base(EntityLogicalName) {
        }
        
        public dia_product_applicationtype(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay(null);
            }
        }
        
        [AttributeLogicalName("dia_product_applicationtypeid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("dia_product_applicationtypeid", value);
            }
        }
        
        [AttributeLogicalName("dia_product_applicationtypeid")]
        public Guid? dia_product_applicationtypeId {
            get {
                return GetAttributeValue<Guid?>("dia_product_applicationtypeid");
            }
            set {
                SetId("dia_product_applicationtypeid", value);
            }
        }
        
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        [AttributeLogicalName("dia_applicationtypeid")]
        public Guid? dia_applicationtypeid {
            get {
                return GetAttributeValue<Guid?>("dia_applicationtypeid");
            }
        }
        
        [AttributeLogicalName("productid")]
        public Guid? productid {
            get {
                return GetAttributeValue<Guid?>("productid");
            }
        }
        
        public static dia_product_applicationtype Retrieve(IOrganizationService service, Guid id, params Expression<Func<dia_product_applicationtype,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
}
